version: "3"
services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container_name
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mate
      - TZ="Asia/Tokyo"
      
    volumes:
      - ../mysql/my.cnf:/etc/mysql/conf.d/my.conf