version: '3'
services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mate
      - TZ="Asia/Tokyo"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
  app:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mate
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ../:/app
volumes:
  db-data:
    
